site_name: MME Online
site_url: https://regensburger-forscher.de/mme
site_description: Online-Tutorial zum MME-Kurs
site_author: Alexander Bazo
copyright: MIT
theme: 
  name: yeti
  custom_dir: mme-template
plugins: 
  - git-revision-date
  - search:
      lang: ["de", "en"]
      prebuild_index: true
extra_javascript:
  - scripts/init.js  
  - scripts/mme-quiz.min.js
extra_css:
  - css/mme-quiz.min.css
markdown_extensions:
  - footnotes
  - admonition
  - attr_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.tilde
nav:
  - Lektionen: 
    - Übersicht: MME/index.md
    - 00 | Der MME-Kurs: 
      - Kursübersicht: MME/00-Class-Introduction/class-introduction.md
      - Lerngruppen: MME/00-Class-Introduction/study-groups.md
    - 01 | Grundlagen der Webentwicklung mit Javascript: MME/01-Basics/index.md
    - 02 | Versionskontrolle in Softwareprojekten: MME/02-Version-Control/index.md
#    - Versionskontrolle mit Git: MME/version-control.md
#    - Progammatische Manipulation des DOM: MME/dom-introduction.md
#    - Codequalität: MME/code-quality.md
#    - Javascript-Anwendungen strukturieren und gestalten: MME/closures-and-module-pattern.md
#    - Den Event-Loop verstehen und verwenden: MME/event-loop.md
#    - Client-Server-Kommunikation (AJAX und XMLHttpRequest): MME/ajax.md
#    - Canvas, Video & Audio: MME/canvas-element.md
#    - Datenspeicherung in Webanwendungen: MME/data-storage.md
#    - Nebenläufigkeit im Browser: MME/webworkers.md
#    - Code Kata: MME/code-kata.md
#    - Einführung in die Node.js-Umgebung: MME/node-js.md
#    - Komplexe Webanwendungen: MME/server-client-applications.md
#    - Anforderungen erheben und dokumentieren: MME/requirements-for-student-projects.md
#    - Pair Programming: MME/pair-programming.md
  - Demos:
    - Simple Color Clicker: Demos/simple-color-clicker.md
#      - Übersicht: Demos/index.md
#      - ToDo-Liste: Demos/todo-list.md
#      - Kanban-Board: Demos/kanban-board.md
#      - Writer: Demos/writer.md
#      - Simon Says: Demos/simon-says.md
#      - Time Tracker: Demos/time-tracker.md
#      - Mensa App: Demos/mensa-app.md
#      - Bundesliga-Tabelle: Demos/bundesliga.md
#      - Ambi Player: Demos/ambi-player.md
#      - ToDo-Liste mit Datenbank: Demos/todo-list-db.md
#      - Writer-Online: Demos/writer-online.md
#      - Chat: Demos/chat.md
#      - Color Clicker: Demos/color-clicker.md
  - Aufgaben: 
      - Übersicht: Aufgaben/index.md
#  - Projekte:
#      - Übersicht: Projekte/index.md
#      - Winter 2019: Projekte/winter-2019.md
  - Reader: Reader/index.md
  - Informationen:
    - Team: team.md
    - Impressum: impress.md
    - Lizenz: licence.md